### ISSUE TITLE
Duplicate binding for ID coE_selected-clusterPlot

### ISSUE THREAD

**Issue by anhvo711** [C3BI-pasteur-fr/UTechSCB-SCHNAPPs#2] opened 2019-07-29 15:47 UTC
I am running the app through runDevApp.R.  The duplicate binding error is preventing loading of the server, and therefore no interaction with the app is possible. Any idea why this happens?

**Comment by baj12** [comment] 2019-10-04 07:34
Hi, sorry missed this post. 
Can you use DEBUG=TRUE and post the error messages you get? There is a lot of output but there should be a clue in there.
When you are using localContributionsDir, please make sure you are referring to a directory that is not including the SCHNAPPs application itself. What is happening is that the whole directory structure is read and if it includes the app itself as well you might be re-reading some of the functionality.

**Comment by baj12** [comment] 2019-10-29 10:37
cannot reproduce without further information. closing. Please open a new ticket with more information.
Thx,
B

**Closed by baj12** 2019-10-29 10:37 UTC
